def show():
  print('\n')
  print('**************************************************************************')
  print('*                                                                        *')
  print('*   1. ajouter un patient                                                *')
  print('*   2. suprimer un patient                                               *')
  print('*   3. ajouter un rendez-vous                                            *')
  print('*   4. annuler un rendez-vous                                            *')
  print('*   5. modifier un rendez-vous                                           *')
  print('*   6. cree une ordonnance                                               *')
  print('*   7. generer les historique des patients existants                     *')
  print('*   8. tracer la courbe de nombre des consultations pour chaque mois.    *')
  print('*   9. tracer la courbe de nombre des consultations pour chaque année.   *')
  print('*   0. quitter                                                           *')
  print('*                                                                        *')
  print('**************************************************************************')
  print('\n')