from .get_patient_id import get_patient_id
from .get_patient_id_positive import get_patient_id_positive
from .get_patient_name import get_patient_name
from .get_patient_gender import get_patient_gender
from .get_patient_age import get_patient_age