from .get_patient_id_not_existing import get_patient_id_not_existing
from .get_patient_id_that_exists import get_patient_id_that_exists
from .get_patient_name import get_patient_name
from .get_patient_gender import get_patient_gender
from .get_patient_age import get_patient_age
